#!/usr/bin/python
# coding: utf-8

# External import

import pandas as pd

# Internal import

from marinedb.utils.allexport import export
from marinedb.utils.printverbose import printv

from marinedb.tools import getcolumnname
from marinedb.tools.temporal import parsedate
from marinedb.tools.temporal import processdateinterval
from marinedb.tools.temporal import splitdate

# Global variable

__all__ = [] # populated using the @export decorator

@export
def apply(df, datekey, yearkey=None, monthkey=None, daykey=None, format=None, stdnan=True, parallel=False, cpu=None,  inplace_parse=False, flag_interval=True, drop_interval=False, inplace_interval=False, strategy_interval='overlap', maxinterval_number=1, maxinterval_level='years', split_date='all', drop_mismatch_split=True, inplace_split=False, dropna_date=False, verbose=True, indent=''):

    params = {
              'drop_empty' : False,
              'verbose': verbose,
              'indent': indent + '   '
             }

    printv('', verbose=verbose)
    printv('** parsedate', verbose=verbose, indent=indent)
    printv('', verbose=verbose)

    # Parse raw date strings

    params_parsedate = {
                        'format': format,
                        'inplace': inplace_parse,
                        'stdnan': stdnan,
                        'parallel': parallel,
                        'cpu': cpu
                       }

    df = parsedate.apply(df, datekey, yearkey=yearkey, monthkey=monthkey, daykey=daykey, **params_parsedate, **params)

    printv('** splitdate', verbose=verbose, indent=indent)
    printv('', verbose=verbose)

    # Process date intervals

    params_processdateinterval = {
                                  'drop_interval': drop_interval,
                                  'strategy': strategy_interval,
                                  'maxinterval_number': maxinterval_number,
                                  'maxinterval_level': maxinterval_level,
                                  'inplace': inplace_interval,
                                  'flag': True
                                 }

    columns_before = set(df.columns)
    basedatekey = datekey.split('_processedby_')[0]

    df = processdateinterval.apply(df, datekey, **params_processdateinterval, **params)

    columns_after = set(df.columns)
    columns_diff = list(columns_after - columns_before)
    columns_diff = [c for c in columns_diff if not (c.startswith(f'{basedatekey}_processedby') or c.startswith('issue_'))]

    # Split date into year, month, and day

    if not inplace_interval:
        # minimizes the number of generated columns
        inplace_split = True

    params_splitdate = {
                        'split': split_date,
                        'drop_mismatch': drop_mismatch_split,
                        'inplace': inplace_split
                       }

    df = splitdate.apply(df, datekey, yearkey=yearkey, monthkey=monthkey, daykey=daykey, **params, **params_splitdate)

    # Drop columns generated by `processdateinterval`

    if not flag_interval:
        df.drop(columns=columns_diff, inplace=True)

    # Drop rows with missing values in the `datekey` column

    if dropna_date:

        df, datekeyout, _ = getcolumnname.apply(df, datekey, '', inplace=True, minimize_columns=False)
        ismissing = pd.isnull(df[datekeyout])
        df = df[~ismissing].reset_index(drop=True)

    return df
