[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "marinedb"
version = "0.0.1"

dependencies = [
    "tqdm>=4.66.1,<5",
    "pandas>=2.2.1,<3.1",
    "numpy>=1.26.3,<2.4",
    "matplotlib>=3.7.1,<3.11",
    "basemap>=1.4.1,<2.1",
    "basemap-data-hires>=1.3.2,<2.1",
    "suds>=1.1.2,<1.3",
    "unidecode>=1.3.8,<2",
    "Levenshtein>=0.25.1,<0.26",
    "PyYAML>=6.0.1,<7",
    "antimeridian==0.4.1",
    "dask==2025.5.1",
    "descartes==1.1.0",
    "h3pandas>=0.3.0,<0.4",
    "h3>=4.2.2,<4.5",
    "joblib>=1.5.1,<2",
    "opencv-python>=4.10.0.84,<4.14",
    "Pillow>=10.2.0,<12.3",
    "psutil>=5.9.8,<7.3",
    "pyarrow>=15.0.2,<24",
    "seaborn>=0.13.2,<0.14",
    "shapely>=2.1.1,<2.2",
    "geopandas>=0.14.4,<1.2",
    "pyproj>=3.6.1,<3.8",
    "fiona>=1.9.6,<1.11",
    "geodatasets>=2026.5.1,<2027",
    "cartopy>=0.25.0,<0.26"
]

[tool.setuptools.packages.find]
where = ["src"] 
# `namespaces` is true by default

[tool.setuptools.package-data]
marinedb = ["*.yaml"]
"marinedb.tools.marineloc" = ["*.sh"]
"marinedb.tools.data" = ["*.yaml", "*.json", "*.npz"]
"marinedb.tools.temporal" = ["*.jar"]
"marinedb.utils" = ["*.sh"]
