[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "marinedb"
version = "0.0.1"

dependencies = [
    "tqdm>=4.66.1",
    "pandas>=2.2.1",
    "numpy>=1.26.3",
    "matplotlib>=3.7.1",
    "basemap>=1.4.1",
    "basemap-data-hires>=1.3.2",
    "suds>=1.1.2",
    "Unidecode>=1.3.8",
    "Levenshtein==0.25.1",
    "PyYAML>=6.0.1",
    "antimeridian==0.4.1",
    "dask==2025.5.1",
    "descartes==1.1.0",
    "h3pandas>=0.3.0",
    "joblib>=1.5.1",
    "opencv_python>=4.10.0.84",
    "Pillow>=10.2.0",
    "psutil>=5.9.8",
    "pyarrow>=15.0.2",
    "seaborn>=0.13.2",
    "shapely>=2.1.1",
    "geopandas>=0.14.4",
    "pyproj>=3.6.1",
    "fiona>=1.9.6",
    "rapidfuzz>=3.9.7",
    "h3>=4.2.2"
]

[tool.setuptools.packages.find]
where = ["src"] 
# `namespaces` is true by default

[tool.setuptools.package-data]
marinedb = ["*.yaml"]
"marinedb.tools.marineloc" = ["*.sh"]
"marinedb.tools.data" = ["*.yaml", "*.json", "*.npz"]
"marinedb.tools.temporal" = ["*.jar"]
"marinedb.utils" = ["*.sh"]
