[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "marinedb"
version = "0.0.1"

dependencies = [
    "tqdm>=4.66.1",
    "pandas>=2.2.1",
    "numpy>=1.26.3",
    "matplotlib>=3.7.1",
    "basemap>=1.4.1",
    "basemap-data-hires>=1.3.2",
    "suds>=1.1.2",
    "Unidecode>=1.3.8",
    "Levenshtein>=0.25.1",
    "PyYAML>=6.0.1"
]

[options]
package_dir = "marinedb"
