data:

  inputfile_path: "/data/smartbiodiv/eberhocoi/experiment_20250418/gbif_marineloc_subset.txt"

  inputdir_path: "/data/smartbiodiv/eberhocoi/experiment_20250418/source"

  outputdir_path: "/data/smartbiodiv/eberhocoi/experiment_20250418/"

  outputfile_path: "marine_clean.txt"


  processing:
    - tool:
        - marineloc:
            datafile: "/data/smartbiodiv/eberhocoi/experiment_20250418/gbif_marineloc_subset.txt"
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            uncompressed_chunks_dir: '/data/smartbiodiv/eberhocoi/experiment_20250418/source/split/'
    - verbatimScientificName:
        - isinworms:
            stdnan: True
            rank_mapping:
              scientificname: 'verbatimScientificName'
              genus: 'genus'
              family: 'family'
              order: 'order'
              cls: 'class'
              phylum: 'phylum'
              kingdom: 'kingdom'
            wormscall:
              - 'scientificname'
              - 'genus'
              - 'family'
              - 'order'
              - 'cls'
              - 'phylum'
              - 'kingdom'
              - 'match_type'
              - 'status'
              - 'valid_AphiaID'
              - 'isExtinct'
              - 'isMarine'
              - 'rank'
              - 'authority'
              - 'unacceptreason'
            worms_dtypes:
              match_type: 'string'
              status: 'string'
              valid_AphiaID: 'Int64'
              isExtinct: 'Int64'
              isMarine: 'Int64'
              rank: 'string'
              authority: 'string'
              unacceptreason: 'string'
            check_ambiguity: True
            fuzzy: True
            fixed_allowedMismatch: False
            verbatimcolumn: ['verbatimScientificName', 'verbatimScientificNameAuthorship']
            verbatimauthorshiponly: [False, True]
            keep_fossil: False
            doublecheck: True
            inplace: False
            resume: True
            resume_mode: 'hard'
            parallel: True
            max_attempt: 15
            drop_nomatch: True
            drop_uncertain: True
    - verbatimScientificName:
        - dropna
    - kingdom:
        - notisin:
            values: ['Bacteria', 'Archaea', 'Viruses']
            flag: False
            dropna: True
        - lettersonly:
            flag: False
            dropna: True
    - phylum:
        - lettersonly:
            flag: False
            dropna: False
    - class:
        - notisin:
            flag: True
            values: ['Aves']
            dropna: False
        - lettersonly:
            flag: False
            dropna: False
    - order:
        - lettersonly:
            flag: False
            dropna: False
    - family:
        - lettersonly:
            flag: False
            dropna: False
    - genus:
        - lettersonly:
            flag: False
            dropna: False
    - basisOfRecord:
        - notisin:
            values: ['OBSERVATION','OCCURRENCE']
            flag: True
    - decimalLatitude:
        - isna:
            flag: False
        - isboundedby:
            operator: '>='
            value: -90
            flag: False
            dropna: True
        - isboundedby:
            operator: '<='
            value: 90
            flag: False
            dropna: True
        - iszero:
            flag: True
            dropna: True
    - decimalLongitude:
        - isna:
            flag: False
        - isboundedby:
            operator: '>='
            value: -180
            flag: False
            dropna: True
        - isboundedby:
            operator: '<='
            value: 180
            flag: False
            dropna: True
        - iszero:
            flag: True
            dropna: True
    - tool:
        - doeslateqlon:
            keylat: 'decimalLatitude'
            keylon: 'decimalLongitude'
            flag: True
            dropna: True
    - tool:
        - isbelow_minlatlonprecision:
            keylat: 'decimalLatitude'
            keylon: 'decimalLongitude'
            value: 2
            flag: True
            dropna: True
    - tool:
        - temporal:
            datekey: 'eventDate'
            yearkey: 'year'
            monthkey: 'month'
            dayley: 'day'
            inplace: False
            flag: True
            stdnan: True
            parallel: True
            dropinterval: False
            strategy: 'overlap'
            maxinterval_number: 1
            maxinterval_level: 'years'
            split: 'all'
            drop_mismatch: True
    - year:
        - isboundedby:
            operator: '>='
            value: 1950
            flag: False
            dropna: True
    - issue:
        - doesnotcontain:
            values: ['ZERO_COORDINATE','COORDINATE_INVALID','COORDINATE_OUT_OF_RANGE','COORDINATE_REPROJECTION_FAILED','RECORDED_DATE_UNLIKELY','RECORDED_DATE_INVALID','INDIVIDUAL_COUNT_CONFLICTS_WITH_OCCURRENCE_STATUS']
            flag: False
            flagname_mapping: ''
            dropna: False
        - doesnotcontain:
            values: ['COORDINATE_REPROJECTION_SUSPICIOUS','GEODETIC_DATUM_INVALID','GEODETIC_DATUM_ASSUMED_WGS84','TAXON_MATCH_NAME_AND_ID_AMBIGUOUS','SCIENTIFIC_NAME_AND_ID_INCONSISTENT','RECORDED_DATE_MISMATCH', 'DEPTH_UNLIKELY', 'DEPTH_MIN_MAX_SWAPPED']
            flag: True
            flagname_mapping: ''
            dropna: False
    - tool:
        - taxasubet:
            lowerbound: 50
            flag: True
            dropna: True
            taxonkey: 'valid_AphiaID'

# PAS FAIT APRÈS !!!!

  #dtype conversion, select & rename columns
  variables:

   #- original_name:
   #    new_name: dtypes
   # OR
   #- original_name: new_name
   # OR
   #- original_name
   #
   # Note:
   # * by default: dtypes=str
   # * `new_name` may be the same as `old_name`

    - decimalLatitude:
        lat: 'float'
    - decimalLongitude:
        lon: 'float'
    - eventDate:
        date: 'datetime' #strings in ISO 8601 date or datetime format only
    - depth:
        depth: 'float'
    - species:
        species: 'str'
    - genus:
        genus: 'str'
    - family:
        family: 'str'
    - order:
        order: 'str'
    - class:
        class: 'str'
    - phylum:
        phylum: 'str'
    - kingdom:
        kingdom: 'str'
    - gbifID:
        gbifID: 'int'
    - occurrenceStatus:
        occurrence_status: 'str'
    - individualCount:
        individual_count: 'int'
    - verbatimScientificName:
        verbatim_species: 'str'
    - issue:
        issue: 'str'
    - datasetKey:
        datasetID: 'str'
    - occurrenceID:
        occurrenceID: 'str'
    - basisOfRecord:
        basisofrecord: 'str'
    - license:
        license: 'str'


  postprocessing:
    - subsample:
        #upperbound: 1000
        lowerbound: 50
