data:

  inputfile_path: "/data/dream/zrr/elena/data/gbif_marine.txt"

  inputdir_path: "/data/dream/zrr/elena/gbif_marinedb/source"

  outputdir_path: "/data/dream/zrr/elena/gbif_marinedb/curated"

  outputfile_path: "gbif_processedby_marinedb.txt"

  processing:
    - verbatimScientificName:
        - createwormsfilters:
            skip_uniques_rebuild: True
            wormscall:
              - 'AphiaID'
              - 'scientificname'
              - 'genus'
              - 'family'
              - 'order'
              - 'cls'
              - 'phylum'
              - 'kingdom'
              - 'match_type'
              - 'status'
              - 'valid_AphiaID'
              - 'lsid'
              - 'isMarine'
              - 'isBrackish'
              - 'authority'
            doublecheck: True
            overwrite: True
            overwrite_parallel: True
            resume: True
            resume_parallel: True
            parallel: True
            max_attempt: 20
        - isinworms:
            stdnan: True
            rank_mapping:
              scientificname: 'verbatimScientificName'
              genus: 'genus'
              family: 'family'
              order: 'order'
              cls: 'class'
              phylum: 'phylum'
              kingdom: 'kingdom'
            worms_dtypes:
              AphiaID: 'Int64'
              match_type: 'string'
              status: 'string'
              valid_AphiaID: 'Int64'
              lsid: 'string'
              isMarine: 'Int64'
              isBrackish: 'Int64'
              authority: 'string'
            check_ambiguity: True
            uncertainty_level: 3
            fuzzy: True
            verbatimcolumn: ['verbatimScientificName', 'verbatimScientificNameAuthorship']
            verbatimauthorshiponly: [False, True]
            keep_fossil: False
            inplace: True
            resume: True
            resume_parallel: True
            resume_mode: 'soft'
            parallel: True
            flag_nomatch: False
            flag_uncertain: False
            store_isinworms: False
    - kingdom:
        - notisin:
            values: ['Bacteria', 'Archaea', 'Viruses']
            flag: False
    - class:
        - isin:
            values: ['Aves']
            flag: True
    - status_generatedby_isinworms:
        - notisin:
            values:
              - 'accepted'
              - 'alternative representation'
              - 'unaccepted'
              - 'unreplaced junior homonym'
              - 'junior homonym'
              - 'superseded combination'
              - 'superseded rank'
            flag: True
            minimize_flagname: True
            flagname_mapping:
              'accepted': 0
              'alternative representation': 1
              'unaccepted': 2
              'unreplaced junior homonym': 3
              'junior homonym': 4
              'superseded combination': 5
              'superseded rank': 6
    - basisOfRecord:
        - mapbasisofrecord:
            inplace: True
        - doesnotcontain:
            values: 'FOSSIL'
            flag: False
    - occurrenceStatus:
        - isin:
            values: ['ABSENT']
            flag: True
            dropna: True
    - tool:
        - islatloninvalid:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: False
            dropna: True
        - islatlonzero:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: False
        - doeslateqlon:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: False
        - belowminlatlonprecision:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            value: 2
            flag: False
    - coordinateUncertaintyInMeters:
        - isboundedby:
            operator: '>'
            value: 1000
            flag: False
            dropna: False
#    - depth:
#        - isna:
#            flag: True
#            stdnan: True
#            stdnan_additional_policy: 'contains_digits'
    - tool:
        - temporal:
            # parse dates
            datekey: 'eventDate'
            yearkey: 'year'
            monthkey: 'month'
            daykey: 'day'
            inplace_parse: True
            stdnan: True
            # process date intervals
            flag_interval: True
            drop_interval: False
            strategy_interval: 'overlap'
            inplace_interval: False
            # split dates
            split_date: 'all'
            drop_mismatch_split: True
            inplace_split: True
            dropna_date: True
        - isdateunlikely:
            yearkey: 'year'
            year_max: 2024
            flag: False
    - year:
        - isna:
            flag: False
        - isboundedby:
            operator: '<'
            value: 1950
            flag: True
    - issue:
        - doesnotcontain:
            values:
              - 'INDIVIDUAL_COUNT_CONFLICTS_WITH_OCCURRENCE_STATUS'
              - 'COORDINATE_REPROJECTION_FAILED'
              - 'PRESUMED_NEGATED_LATITUDE'
              - 'PRESUMED_SWAPPED_COORDINATE'
              - 'PRESUMED_NEGATED_LONGITUDE'
              - '(?:(?:COUNTRY|CONTINENT)_COORDINATE_MISMATCH.*?GEODETIC_DATUM_INVALID)|(?:GEODETIC_DATUM_INVALID.*?(?:COUNTRY|CONTINENT)_COORDINATE_MISMATCH)'
            flag: False
        - contains:
            values:
              - 'GEODETIC_DATUM_INVALID'
            flag: True
#        - contains:
#          # See the limitations of GBIF's depth-processing workflow discussed in the article
#            values:
#              - 'DEPTH_UNLIKELY'
#              - 'DEPTH_NON_NUMERIC'
#              - 'DEPTH_NOT_METRIC'
#            flag: True
#            minimize_flagname: True
#            flagname_mapping:
#              'DEPTH_UNLIKELY': 0
#              'DEPTH_NON_NUMERIC': 1
#              'DEPTH_NOT_METRIC': 2

  variables:

    - gbifID:
        gbif_id: 'int'
    - decimalLatitude:
        decimalLatitude: 'float'
    - decimalLongitude:
        decimalLongitude: 'float'
    - eventDate
    - year:
        year: 'int'
    - month:
        month: 'int'
    - day:
        day: 'int'
#    - depth:
#        depth: 'float'
#    - depthAccuracy:
#        depthAccuracy: 'float'
    - verbatimScientificName: species
    - genus
    - family
    - order
    - class
    - phylum
    - kingdom
    - basisOfRecord
    - flag_occurrenceStatus_isin_ABSENT:
        flag_absence: 'bool'
#    - individualCount:
#        individualCount: 'int'
#    - issue:
#        gbif_issue: 'str'
    - license
    - flag_status_generatedby_isinworms_notisin_0-1-2-3-4-5-6:
        flag_status_generatedby_isinworms_notfitforuse: 'bool'
#    - flag_issue_contains_0-1-2:
#        flag_depth_issue: 'bool'
    - datasetKey        # OBIS/GBIF/JeDI overlap
    - occurrenceID      # OBIS/GBIF/JeDI overlap
    - publishingOrgKey  # OBIS/GBIF/JeDI overlap
    - institutionCode   # OBIS/GBIF/JeDI overlap
    - collectionCode    # OBIS/GBIF/JeDI overlap
    - catalogNumber     # OBIS/GBIF/JeDI overlap
    - recordNumber      # OBIS/GBIF/JeDI overlap

  postprocessing:
    - tool:
      - resolvetaxamatch:
          review_level: 3
    - tool:
      - taxasubset:
          lowerbound: 50
          flag: True
          dropna: True
