data:

  inputfile_path: "/data/dream/zrr/elena/data/obis_marine.txt"

  inputdir_path: "/data/dream/zrr/elena/obis_marinedb/source"

  outputdir_path: "/data/dream/zrr/elena/obis_marinedb/curated"

  outputfile_path: "obis_processedby_marinedb.txt"

  processing:
    - species:
        - createwormsfilters:
            skip_uniques_rebuild: True
            wormscall:
              - 'AphiaID'
              - 'scientificname'
              - 'genus'
              - 'family'
              - 'order'
              - 'cls'
              - 'phylum'
              - 'kingdom'
              - 'match_type'
              - 'status'
              - 'valid_AphiaID'
              - 'lsid'
              - 'isMarine'
              - 'isBrackish'
              - 'authority'
            doublecheck: True
            overwrite: True
            resume: True
            parallel: True
            max_attempt: 20
        - isinworms:
            stdnan: True
            rank_mapping:
              scientificname: 'species'
              genus: 'genus'
              family: 'family'
              order: 'order'
              cls: 'class'
              phylum: 'phylum'
              kingdom: 'kingdom'
            worms_dtypes:
              AphiaID: 'Int64'
              match_type: 'string'
              status: 'string'
              valid_AphiaID: 'Int64'
              lsid: 'string'
              isMarine: 'Int64'
              isBrackish: 'Int64'
              rank: 'string'
              authority: 'string'
            check_ambiguity: True
#            uncertainty_level: 3
            fuzzy: True
            verbatimcolumn: ['scientificName', 'scientificNameAuthorship', 'originalScientificName']
            verbatimauthorshiponly: [False, True, False]
            keep_fossil: False
            inplace: True
            resume: True
            resume_mode: 'soft'
            parallel: True
            flag_nomatch: False
            flag_uncertain: False
            store_isinworms: False
    - kingdom:
        - notisin:
            values: ['Bacteria', 'Archaea', 'Viruses']
            flag: False
    - class:
        - isin:
            values: ['Aves']
            flag: True
    - status_generatedby_isinworms:
        - notisin:
            values:
              - 'accepted'
              - 'alternative representation'
              - 'unaccepted'
              - 'unreplaced junior homonym'
              - 'junior homonym'
              - 'superseded combination'
              - 'superseded rank'
            flag: True
            minimize_flagname: True
            flagname_mapping:
              'accepted': 0
              'alternative representation': 1
              'unaccepted': 2
              'unreplaced junior homonym': 3
              'junior homonym': 4
              'superseded combination': 5
              'superseded rank': 6
    - basisOfRecord:
        - mapbasisofrecord:
            inplace: True
        - notisin:
            values: 'FOSSIL_SPECIMEN'
            flag: False
    - occurrenceStatus:
        - isin:
            values: ['absent','not observed','Absence','pseudo-absent','Ausent']
            flag: True
            dropna: False
            minimize_flagname: True
            flagname_mapping:
              'absent': 0
              'not observed': 1
              'Absence': 2
              'pseudo-absent': 3
              'Ausent': 4
    - tool:
        - islatloninvalid: # excluded at data acquisition
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: False
            dropna: True
        - islatlonzero:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: False
        - doeslateqlon:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: False
        - belowminlatlonprecision:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            value: 2
            flag: False
    - coordinateUncertaintyInMeters:
        - isboundedby:
            operator: '<='
            value: 1000
            flag: False
            dropna: False
#    - minimumDepthInMeters:
#        - isna:
#            flag: True
#            stdnan: True
#            stdnan_additional_policy: 'contains_digits'
#    - maximumDepthInMeters:
#        - isna:
#            flag: True
#            stdnan: True
#            stdnan_additional_policy: 'contains_digits'
    - tool:
        - temporal:
            # parse dates
            datekey: 'eventDate'
            yearkey: 'year'
            monthkey: 'month'
            daykey: 'day'
            inplace_parse: True
            stdnan: True
            # process date intervals
            flag_interval: True
            drop_interval: False
            strategy_interval: 'overlap'
            inplace_interval: False
            # split dates
            split_date: 'all'
            drop_mismatch_split: True
            inplace_components_split: True
            inplace_date_split: True
            dropna_date: True
        - isdateunlikely:
            yearkey: 'year'
            year_max: 2025
            flag: False
    - year:
        - isna:
            flag: False
        - isboundedby:
            operator: '<'
            value: 1950
            flag: True
    - flags:
        - doesnotcontain:
            values:
              - 'DATE_IN_FUTURE'
              - 'ON_LAND'
            flag: False
#        - contains:
#            values:
#              - 'DEPTH_EXCEEDS_BATH'
#              - 'MIN_DEPTH_EXCEEDS_MAX'
#              - 'DEPTH_OUT_OF_RANGE'
#            flag: True
#            minimize_flagname: True
#            flagname_mapping:
#              'DEPTH_EXCEEDS_BATH': 0
#              'MIN_DEPTH_EXCEEDS_MAX': 1
#              'DEPTH_OUT_OF_RANGE': 2

  variables:

    - id:
        obis_id: 'str'
    - decimalLatitude:
        decimalLatitude: 'float'
    - decimalLongitude:
        decimalLongitude: 'float'
    - eventDate
    - year:
        year: 'int'
    - month:
        month: 'int'
    - day:
        day: 'int'
    - minimumDepthInMeters:
        minimumDepthInMeters: 'float'
    - maximumDepthInMeters:
        maximumDepthInMeters: 'float'
    - depth
    - verbatimDepth
    - species
    - genus
    - family
    - order
    - class
    - phylum
    - kingdom
    - basisOfRecord
    - flag_occurrenceStatus_isin_0-1-2-3-4:
        flag_absence: 'bool'
    - flags:
        obis_issue: 'str'
    - license
    - accessRights
    - flag_status_generatedby_isinworms_notisin_0-1-2-3-4-5-6:
        flag_status_generatedby_isinworms_notfitforuse: 'bool'
#    - flag_flags_contains_0-1-2:
#        flag_depth_issue: 'bool'
    - dataset_id            # OBIS/GBIF/JeDI overlap
    - datasetID             # OBIS/GBIF/JeDI overlap
    - occurrenceID          # OBIS/GBIF/JeDI overlap
    - ownerInstitutionCode  # OBIS/GBIF/JeDI overlap
    - institutionID         # OBIS/GBIF/JeDI overlap
    - collectionID          # OBIS/GBIF/JeDI overlap
    - institutionCode       # OBIS/GBIF/JeDI overlap
    - collectionCode        # OBIS/GBIF/JeDI overlap
    - catalogNumber         # OBIS/GBIF/JeDI overlap

  postprocessing:
#    - tool:
#      - resolvetaxamatch:
#          review_level: 3
    - tool:
      - taxasubset:
          lowerbound: 50
          flag: True
          dropna: True
