data:

  inputfile_path: "/mnt/smartbiodiv/gbifbuilding/gbif_marine.txt.gz"

  inputdir_path: "/data/smartbiodiv/eberhocoi/gbif_marinedb/source"

  outputdir_path: "/data/smartbiodiv/eberhocoi/gbif_marinedb/flag"

  outputfile_path: "gbif_processedby_marinedb.txt"

  processing:
    - verbatimScientificName:
        - createwormsfilters:
            wormscall:
              - 'scientificname'
              - 'genus'
              - 'family'
              - 'order'
              - 'cls'
              - 'phylum'
              - 'kingdom'
              - 'match_type'
              - 'status'
              - 'valid_AphiaID'
#              - 'lsid'
              - 'isExtinct'
              - 'isMarine'
              - 'rank'
              - 'authority'
              - 'unacceptreason'
            identification_level: 'species'
            doublecheck: True
            overwrite: True
            overwrite_parallel: True
            resume: True
            resume_parallel: True
            parallel: True
            max_attempt: 20
        - isinworms:
            stdnan: True
            rank_mapping:
              scientificname: 'verbatimScientificName'
              genus: 'genus'
              family: 'family'
              order: 'order'
              cls: 'class'
              phylum: 'phylum'
              kingdom: 'kingdom'
            worms_dtypes:
              match_type: 'string'
              status: 'string'
              valid_AphiaID: 'Int64'
#              lsid: 'string'
              isExtinct: 'Int64'
              isMarine: 'Int64'
              rank: 'string'
              authority: 'string'
              unacceptreason: 'string'
            check_ambiguity: True
            fuzzy: True
            verbatimcolumn: ['verbatimScientificName', 'verbatimScientificNameAuthorship']
            verbatimauthorshiponly: [False, True]
            keep_fossil: True
            inplace: False
            resume: True
            resume_parallel: True
            resume_mode: 'soft'
            parallel: True
            flag_nomatch: True
            flag_uncertain: True
            store_isinworms: False
    - kingdom:
        - isin:
            values: ['Bacteria', 'Archaea', 'Viruses']
            flag: True
    - class:
        - isin:
            values: ['Aves']
            flag: True
    - basisOfRecord:
        - isin:
            values: ['OBSERVATION','OCCURRENCE']
            flag: True
    - tool:
        - islatloninvalid: # excluded at data acquisition
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: True
            dropna: True
        - islatlonzero:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: True
        - doeslateqlon:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: True
        - isbelow_minlatlonprecision:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            value: 2
            flag: True
#    - depth:
#        - isna:
#            flag: True
    - tool:
        - temporal:
            # parse dates
            datekey: 'eventDate'
            yearkey: 'year'
            monthkey: 'month'
            daykey: 'day'
            inplace: False
            stdnan: True
            # process date intervals
            flag_interval: True
            drop_interval: False
            strategy_interval: 'overlap'
            # split dates
            split_date: 'all'
            drop_mismatch_split: False # should not occur
            dropna_date: False
        - isdateunlikely: # excluded at data acquisition
            yearkey: 'year'
            flag: True
    - year:
        - isna:
            flag: True
        - isboundedby:
            operator: '<'
            value: 1950
            flag: True
    - issue:
        - contains:
            values:
              - 'COORDINATE_INVALID' # none should be present, excluded at data acquisition
              - 'COORDINATE_OUT_OF_RANGE' # none should be present, excluded at data acquisition
              - 'COORDINATE_REPROJECTION_FAILED' # marginal, not excluded at data acquisition, but removed during the processing stage (if replaced by NaN) 
              - 'ZERO_COORDINATE' # none should be present, removed during the processing stage
              - 'RECORDED_DATE_UNLIKELY' # none should be present, removed during the processing stage
              - 'RECORDED_DATE_INVALID' # none should be present, removed during the processing stage
              - 'INDIVIDUAL_COUNT_CONFLICTS_WITH_OCCURRENCE_STATUS' # marginal
            flag: True
            minimize_flagname: True
        - contains:
            values:
              - 'COORDINATE_REPROJECTION_SUSPICIOUS'
              - 'GEODETIC_DATUM_INVALID' # more prevalent in GBIF marine data, exclusion may be overly strict
              - 'COUNTRY_COORDINATE_MISMATCH'
              - 'CONTINENT_COORDINATE_MISMATCH'
              - 'DEPTH_UNLIKELY'
              - 'RECORDED_DATE_MISMATCH'
            flag: True
            minimize_flagname: True
    - occurrenceStatus:
        - isin:
            values: ['ABSENT']
            flag: True

  # dtype conversion, select & rename columns

  variables:

   #- original_name:
   #    new_name: dtypes
   # OR
   #- original_name: new_name
   # OR
   #- original_name
   #
   # Note:
   # * by default: dtypes=str
   # * `new_name` may be the same as `old_name`

    - gbifID:
        gbifID: 'int'
    - decimalLatitude:
        decimalLatitude: 'float'
    - decimalLongitude:
        decimalLongitude: 'float'
    - eventDate
    - year:
        year: 'int'
    - month:
        month: 'int'
    - day:
        day: 'int'
    - depth:
        depth: 'float'
    - verbatimScientificName: species
    - genus
    - family
    - order
    - class
    - phylum
    - kingdom
    - basisOfRecord
    - occurrenceStatus:
        occurrenceStatus: 'str'
#    - individualCount:
#        individualCount: 'int'
    - issue:
        gbif_issue: 'str'
#    - license
    - datasetKey        # OBIS/GBIF/JeDI overlap
    - occurrenceID      # OBIS/GBIF/JeDI overlap
    - publishingOrgKey  # OBIS/GBIF/JeDI overlap
    - institutionCode   # OBIS/GBIF/JeDI overlap
    - collectionCode    # OBIS/GBIF/JeDI overlap
    - catalogNumber     # OBIS/GBIF/JeDI overlap
    - recordNumber      # OBIS/GBIF/JeDI overlap
    - marinedb_mask:
        marinedb_mask: 'int'

  postprocessing:
    - tool:
      - resolvetaxamatch
    - tool:
      - taxasubset:
          lowerbound: 50
          flag: True
          store: True
