data:

  inputfile_path: "/data/smartbiodiv/eberhocoi/jedi/JeDI.csv"

  inputdir_path: "/data/smartbiodiv/eberhocoi/jedi_marinedb/source"

  outputdir_path: "/data/smartbiodiv/eberhocoi/jedi_marinedb"

  outputfile_path: "jedi_processedby_marinedb.txt"

  processing:
    - tool:
        - format:
            dataset_name: 'jedi'
            overwrite: False
    - scientificName:
        - createwormsfilters:
            wormscall:
              - 'scientificname'
              - 'genus'
              - 'family'
              - 'order'
              - 'cls'
              - 'phylum'
              - 'kingdom'
              - 'match_type'
              - 'status'
              - 'valid_AphiaID'
              - 'isExtinct'
              - 'isMarine'
              - 'rank'
              - 'authority'
              - 'unacceptreason'
            identification_level: 'species'
            doublecheck: True
            overwrite: True
            overwrite_parallel: True
            resume: True
            resume_parallel: True
            parallel: True
            max_attempt: 20
        - isinworms:
            stdnan: True
            rank_mapping:
              scientificname: 'scientificName'
              genus: 'genus'
              family: 'family'
              order: 'order'
              cls: 'class'
              phylum: 'phylum'
              kingdom: 'kingdom'
            worms_dtypes:
              match_type: 'string'
              status: 'string'
              valid_AphiaID: 'Int64'
              isExtinct: 'Int64'
              isMarine: 'Int64'
              rank: 'string'
              authority: 'string'
              unacceptreason: 'string'
            check_ambiguity: True
            fuzzy: True
            keep_fossil: False
            inplace: True
            resume: True
            resume_parallel: True
            resume_mode: 'soft'
#            store_createwormsfilters: True
#            store_parallel_createwormsfilters: True
            parallel: True
            flag_nomatch: False
            flag_uncertain: True
            store_isinworms: False
            overwrite_isinworms: False
        - isna:
            flag: False
    - kingdom:
        - notisin:
            values: ['Bacteria', 'Archaea', 'Viruses']
            flag: False
            dropna: True
#        - lettersonly:
#            flag: False
#            dropna: True
#    - phylum:
#        - lettersonly:
#            flag: False
#            dropna: False
    - class:
        - notisin:
            values: ['Aves']
            flag: True
            dropna: False
#        - lettersonly:
#            flag: False
#            dropna: False
#    - order:
#        - lettersonly:
#            flag: False
#            dropna: False
#    - family:
#        - lettersonly:
#            flag: False
#            dropna: False
#    - genus:
#        - lettersonly:
#            flag: False
#            dropna: False
    - samplingProtocol:
        - mapbasisofrecord:
            inplace: False
        - notisin:
            values: ['OBSERVATION','OCCURRENCE']
            flag: True
            dropna: False
    - tool:
        - islatloninvalid:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: False
            dropna: True
#    - decimalLatitude:
#        - isna:
#            flag: False
#        - isboundedby:
#            operator: '>='
#            value: -90
#            flag: False
#            dropna: True
#        - isboundedby:
#            operator: '<='
#            value: 90
#            flag: False
#            dropna: True
#        - iszero:
#            flag: False
#            dropna: True
#    - decimalLongitude:
#        - isna:
#            flag: False
#        - isboundedby:
#            operator: '>='
#            value: -180
#            flag: False
#            dropna: True
#        - isboundedby:
#            operator: '<='
#            value: 180
#            flag: False
#            dropna: True
#        - iszero:
#            flag: False
#            dropna: True
        - islatlonzero:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: False
            dropna: True
        - doeslateqlon:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            flag: False
            dropna: True
        - isbelow_minlatlonprecision:
            latkey: 'decimalLatitude'
            lonkey: 'decimalLongitude'
            value: 2
            flag: False
            dropna: True
#    - verbatimDepth:
#        - isna:
#            flag: True
    - tool:
        - temporal:
            # parse dates
            datekey: 'eventDate'
            yearkey: 'year'
            monthkey: 'month'
            daykey: 'day'
            inplace: True
            stdnan: True
            # process date intervals
            flag_interval: True
            drop_interval: False
            strategy_interval: 'overlap'
            maxinterval_number: 1
            maxinterval_level: 'years'
            # split dates
            split_date: 'all'
            drop_mismatch_split: False
            dropna_date: True
#        - isdateinvalid:
#            yearkey: 'year'
#            monthkey: 'month'
#            daykey: 'day'
#            flag: False
#            dropna: True
        - isdateunlikely:
            yearkey: 'year'
            flag: False
            dropna: True
    - year:
#        - isboundedby:
#            operator: '>='
#            value: 1700
#            flag: False
#            dropna: True
        - isboundedby:
            operator: '>='
            value: 1950
            flag: True
            dropna: True
    - occurrenceStatus:
        - isin:
            values: 'absent'
            flag: True
            dropna: False

  # dtype conversion, select & rename columns

  variables:

   #- original_name:
   #    new_name: dtypes
   # OR
   #- original_name: new_name
   # OR
   #- original_name
   #
   # Note:
   # * by default: dtypes=str
   # * `new_name` may be the same as `old_name`

    - decimalLatitude:
        decimalLatitude: 'float'
    - decimalLongitude:
        decimalLongitude: 'float'
    - eventDate
    - year:
        year: 'int'
    - month:
        month: 'int'
    - day:
        day: 'int'
    - verbatimDepth:
        Depth: 'float'
    - scientificName:
        species: 'str'
    - genus
    - family
    - order
    - class
    - phylum
    - kingdom
    - basisOfRecord
    - occurrenceStatus
    - collectionCode        # OBIS/GBIF/JeDI overlap
    - ownerInstitutionCode  # OBIS/GBIF/JeDI overlap

  postprocessing:
    - tool:
      - resolvetaxamatch
    - tool:
      - taxasubset:
          lowerbound: 50
          flag: True
          store: True
          dropna: False
